In [5]:
import numpy as np

In [6]:
scores=np.array([[85,90,78],
                [92,88,95],
                [76,95,85],
                [90,85,92],
                [88,76,89]])
mean_scores=np.mean(scores,axis=0)
print(mean_scores)
                   

[86.2 86.8 87.8]


In [7]:
scores=np.array([[85,90,78],
                [92,88,95],
                [76,95,85],
                [90,85,92],
                [88,76,89]])
median_scores=np.median(scores,axis=0)
print(median_scores)

[88. 88. 89.]


In [8]:
scores=np.array([[85,90,78],
                [92,88,95],
                [76,95,85],
                [90,85,92],
                [88,76,89]])
sum_scores=np.sum(scores,axis=0)
print(sum_scores)

[431 434 439]


In [9]:
scores=np.array([[85,90,78],
                [92,88,95],
                [76,95,85],
                [90,85,92],
                [88,76,89]])
min_scores=np.min(scores,axis=0)
print(min_scores)

[76 76 78]


In [10]:
scores=np.array([[85,90,78],
                [92,88,95],
                [76,95,85],
                [90,85,92],
                [88,76,89]])
max_scores=np.max(scores,axis=0)
print(max_scores)

[92 95 95]


In [11]:
sorted_scores=np.sort(scores,axis=0)
print(sorted_scores)

[[76 76 78]
 [85 85 85]
 [88 88 89]
 [90 90 92]
 [92 95 95]]


In [15]:
scores.reshape(3,5)

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])