In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
Z=np.zeros(5)

In [5]:
Z

array([0., 0., 0., 0., 0.])

In [6]:
ar=np.arange(0,10,1)

In [7]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
ran=np.random.rand(4)

In [9]:
ran

array([0.73017115, 0.45442983, 0.72758064, 0.80742319])

In [10]:
ln=np.linspace(0,100,10)

In [11]:
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

2D array

In [13]:
ar2=np.array(([1,2,3],[4,5,6],[7,8,9]))

ar2

In [14]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar2=np.array([1,4,])

In [16]:
ar2

array([1, 4])

In [17]:
o1=np.ones([5,5])

In [18]:
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
I=np.eye(5)

In [20]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
r1=np.random.rand(4,5)

In [22]:
r1

array([[0.67636537, 0.25045139, 0.65126343, 0.67872052, 0.22517079],
       [0.72934486, 0.03699009, 0.98904455, 0.65570231, 0.93495397],
       [0.58735113, 0.09786796, 0.81886798, 0.48680171, 0.67666477],
       [0.69012386, 0.21976589, 0.04671774, 0.18946409, 0.89841733]])

In [23]:
c1=np.random.rand(4,6)

In [24]:
c1

array([[0.8003867 , 0.44741723, 0.18738734, 0.95175418, 0.05726222,
        0.65900861],
       [0.1697371 , 0.91129198, 0.133562  , 0.47085158, 0.60535419,
        0.57710708],
       [0.81495421, 0.16005424, 0.74514774, 0.26909647, 0.49562299,
        0.82494291],
       [0.01581607, 0.81419215, 0.14162138, 0.25024791, 0.21648678,
        0.4503524 ]])

In [25]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ar2

array([1, 4])

In [27]:
print(ar.size)

10


In [28]:
print(ar2.size)

2


In [29]:
print(ar.shape)

(10,)


In [30]:
print(ar2.shape)

(2,)


# Opertions in Array 

In [ ]:
copy

mark

replace


In [34]:
ar3[1,2]=12
ar3[0,1]=15

NameError: name 'ar3' is not defined

In [35]:
ar3[1,2]=12
ar3[0,1]=15

NameError: name 'ar3' is not defined

In [36]:
ar3=np.sort(ar3,axis=0)

NameError: name 'ar3' is not defined

In [37]:
ar3=np.copy(ar2)

In [38]:
ar3

array([1, 4])

In [39]:
ar3=ar3.T

In [40]:
ar3

array([1, 4])

In [41]:
ar3[2,2]=10

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [42]:
ar3[2,2]=10

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [43]:
ar3[1,2]=10

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [44]:
arr3

NameError: name 'arr3' is not defined

In [45]:
ar4=np.random.rand(99)

In [46]:
ar4

array([0.80192504, 0.65456343, 0.4934348 , 0.51858761, 0.12061012,
       0.98323054, 0.69816096, 0.99163413, 0.96772216, 0.1767533 ,
       0.36444512, 0.44029572, 0.66951018, 0.12850682, 0.46188652,
       0.1021064 , 0.52170185, 0.96020789, 0.74258195, 0.68706533,
       0.76904496, 0.90308098, 0.46480502, 0.66665215, 0.2744983 ,
       0.58763044, 0.21989223, 0.17605535, 0.50680298, 0.20998502,
       0.23091079, 0.4662965 , 0.06496061, 0.69678225, 0.09567678,
       0.8058299 , 0.43480768, 0.62504088, 0.85199477, 0.80976498,
       0.8646039 , 0.27482822, 0.15286172, 0.701307  , 0.34591384,
       0.91937649, 0.22557462, 0.38803606, 0.21498946, 0.11986369,
       0.29660352, 0.81770696, 0.75991941, 0.27184848, 0.99458662,
       0.25051643, 0.19335626, 0.54301085, 0.53558486, 0.90735057,
       0.0168451 , 0.93878615, 0.47401112, 0.0565462 , 0.8059905 ,
       0.7489715 , 0.6796489 , 0.41759452, 0.43525291, 0.04436297,
       0.26233691, 0.67153781, 0.33896158, 0.05338822, 0.39335

In [47]:
ar4.size

99

In [48]:
ar4=ar4.reshape(11,9)

In [49]:
ar4.shape

(11, 9)

In [51]:
ar4=ar4

In [52]:
ar4

array([[0.80192504, 0.65456343, 0.4934348 , 0.51858761, 0.12061012,
        0.98323054, 0.69816096, 0.99163413, 0.96772216],
       [0.1767533 , 0.36444512, 0.44029572, 0.66951018, 0.12850682,
        0.46188652, 0.1021064 , 0.52170185, 0.96020789],
       [0.74258195, 0.68706533, 0.76904496, 0.90308098, 0.46480502,
        0.66665215, 0.2744983 , 0.58763044, 0.21989223],
       [0.17605535, 0.50680298, 0.20998502, 0.23091079, 0.4662965 ,
        0.06496061, 0.69678225, 0.09567678, 0.8058299 ],
       [0.43480768, 0.62504088, 0.85199477, 0.80976498, 0.8646039 ,
        0.27482822, 0.15286172, 0.701307  , 0.34591384],
       [0.91937649, 0.22557462, 0.38803606, 0.21498946, 0.11986369,
        0.29660352, 0.81770696, 0.75991941, 0.27184848],
       [0.99458662, 0.25051643, 0.19335626, 0.54301085, 0.53558486,
        0.90735057, 0.0168451 , 0.93878615, 0.47401112],
       [0.0565462 , 0.8059905 , 0.7489715 , 0.6796489 , 0.41759452,
        0.43525291, 0.04436297, 0.26233691, 0.67153781],


In [53]:
ar4.shape

(11, 9)

In [54]:
ar3

array([1, 4])

In [55]:
ar3=ar4.T

In [56]:
ar3

array([[0.80192504, 0.1767533 , 0.74258195, 0.17605535, 0.43480768,
        0.91937649, 0.99458662, 0.0565462 , 0.33896158, 0.36598729,
        0.17221764],
       [0.65456343, 0.36444512, 0.68706533, 0.50680298, 0.62504088,
        0.22557462, 0.25051643, 0.8059905 , 0.05338822, 0.76957282,
        0.72122946],
       [0.4934348 , 0.44029572, 0.76904496, 0.20998502, 0.85199477,
        0.38803606, 0.19335626, 0.7489715 , 0.3933566 , 0.58504677,
        0.92340055],
       [0.51858761, 0.66951018, 0.90308098, 0.23091079, 0.80976498,
        0.21498946, 0.54301085, 0.6796489 , 0.9812829 , 0.08792853,
        0.4069833 ],
       [0.12061012, 0.12850682, 0.46480502, 0.4662965 , 0.8646039 ,
        0.11986369, 0.53558486, 0.41759452, 0.21048646, 0.34482484,
        0.44583638],
       [0.98323054, 0.46188652, 0.66665215, 0.06496061, 0.27482822,
        0.29660352, 0.90735057, 0.43525291, 0.48859781, 0.9303576 ,
        0.81420803],
       [0.69816096, 0.1021064 , 0.2744983 , 0.69678225, 0.

In [57]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
ar=np.append(ar,10)

In [61]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
ar=np.delete(ar,6,axis=0)

In [63]:
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [65]:
ar=np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [66]:
ar2

array([1, 4])

In [67]:
ar3

array([[0.80192504, 0.1767533 , 0.74258195, 0.17605535, 0.43480768,
        0.91937649, 0.99458662, 0.0565462 , 0.33896158, 0.36598729,
        0.17221764],
       [0.65456343, 0.36444512, 0.68706533, 0.50680298, 0.62504088,
        0.22557462, 0.25051643, 0.8059905 , 0.05338822, 0.76957282,
        0.72122946],
       [0.4934348 , 0.44029572, 0.76904496, 0.20998502, 0.85199477,
        0.38803606, 0.19335626, 0.7489715 , 0.3933566 , 0.58504677,
        0.92340055],
       [0.51858761, 0.66951018, 0.90308098, 0.23091079, 0.80976498,
        0.21498946, 0.54301085, 0.6796489 , 0.9812829 , 0.08792853,
        0.4069833 ],
       [0.12061012, 0.12850682, 0.46480502, 0.4662965 , 0.8646039 ,
        0.11986369, 0.53558486, 0.41759452, 0.21048646, 0.34482484,
        0.44583638],
       [0.98323054, 0.46188652, 0.66665215, 0.06496061, 0.27482822,
        0.29660352, 0.90735057, 0.43525291, 0.48859781, 0.9303576 ,
        0.81420803],
       [0.69816096, 0.1021064 , 0.2744983 , 0.69678225, 0.

SyntaxError: unmatched ')' (2690021779.py, line 1)

ValueError: array split does not result in an equal division

NameError: name 'ar6' is not defined

In [72]:
ar1

NameError: name 'ar1' is not defined

In [73]:
ar1

NameError: name 'ar1' is not defined

In [74]:
ar2

array([1, 4])

In [75]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [80]:
np.add(ar2,1)

array([2, 5])

In [83]:
ar2 

array([1, 4])

In [84]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [91]:
np.subtract(ar2,1)

array([0, 3])

In [92]:
np.ceil(ar2)

array([1., 4.])

In [93]:
np.floor(ar2)

array([1., 4.])

In [94]:
np.round(ar2)

array([1, 4])

In [95]:
np.mean(ar2)

2.5

In [97]:
np.mean(ar2,axis=0)

2.5

In [99]:
np.mean(ar2,axis=0)

2.5

In [100]:
np.median(ar2)

2.5

In [101]:
np.min(ar2)

1

In [102]:
np.max(ar2)

4

In [103]:
ar10=np.array([2,5,3,8,0,4,1,6,9])

In [104]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [105]:
np.argmax(ar10)

8

In [106]:
np.argmin(ar10)

4

In [107]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8], dtype=int64)

In [108]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])

In [109]:
np.log(ar10)

C:\Users\student\AppData\Local\Temp\ipykernel_10460\168028880.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar10)


array([0.69314718, 1.60943791, 1.09861229, 2.07944154,       -inf,
       1.38629436, 0.        , 1.79175947, 2.19722458])